---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@2fb8b15d5e72caaea35cc5e4541733d87ef66002 # 20261008.0
    with:
      smoke-test: |-
        ./dist/momentum --help
        ./dist/momentum --version
