---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@fcc6d0528cf0533614d1162c5c5b8ebbb6dfdad5 # 20261008.1
    with:
      smoke-test: |-
        ./dist/momentum --help
        ./dist/momentum --version
