---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request: {}
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/build-bun-cli.yml@2fb2fa1ffdd2f4808768bf86828482660e366a13 # 20261008.3
    with:
      smoke-test: |-
        ./dist/momentum --help
        ./dist/momentum --version
